#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$project_root/scripts/version.sh"
# Resolve customizable product metadata.
product_name="${APP_NAME:-CodexBuddy}"
bundle_identifier="${BUNDLE_ID:-com.zhouxuan3550.codexbuddy}"
release_version="${VERSION:-$APP_VERSION}"
release_build="${BUILD_NUMBER:-$APP_BUILD_NUMBER}"
target_architectures="${ARCHS:-arm64 x86_64}"
icon_source="${ICON_SOURCE:-$project_root/assets/CodexBuddyIcon.png}"
output_root="$project_root/build"
application_bundle="$output_root/$product_name.app"
contents="$application_bundle/Contents"
executable_directory="$contents/MacOS"
resources="$contents/Resources"
iconset="$output_root/CodexBuddy.iconset"
# Recreate only the bundle-specific output directories.
rm -rf "$application_bundle" "$iconset"
mkdir -p "$executable_directory" "$resources"

compile_architecture() {
  local architecture="$1"
  local binary="$output_root/$product_name-$architecture"
  local cache="$output_root/SwiftModuleCache-$architecture"
  rm -rf "$binary" "$cache"
  mkdir -p "$cache"
  xcrun --sdk macosx swiftc \
    -O \
    -target "$architecture-apple-macos13.0" \
    -module-cache-path "$cache" \
    -framework AppKit \
    -framework Charts \
    -framework Combine \
    -framework CoreServices \
    -framework ServiceManagement \
    -framework SwiftUI \
    -framework UserNotifications \
    "$project_root/CodexBuddy/"*.swift \
    -o "$binary"
  compiled_binaries+=("$binary")
}

compiled_binaries=()
for architecture in $target_architectures; do
  compile_architecture "$architecture"
done

if (( ${#compiled_binaries[@]} == 1 )); then
  cp "${compiled_binaries[0]}" "$executable_directory/$product_name"
else
  xcrun lipo -create "${compiled_binaries[@]}" -output "$executable_directory/$product_name"
fi

create_icon() {
  [[ -f "$icon_source" ]] || return 0
  mkdir -p "$iconset"
  local points pixels filename
  for specification in \
    "16 16 icon_16x16.png" \
    "16 32 icon_16x16@2x.png" \
    "32 32 icon_32x32.png" \
    "32 64 icon_32x32@2x.png" \
    "128 128 icon_128x128.png" \
    "128 256 icon_128x128@2x.png" \
    "256 256 icon_256x256.png" \
    "256 512 icon_256x256@2x.png" \
    "512 512 icon_512x512.png" \
    "512 1024 icon_512x512@2x.png"; do
    read -r points pixels filename <<< "$specification"
    sips -z "$pixels" "$pixels" "$icon_source" --out "$iconset/$filename" >/dev/null
  done
  iconutil -c icns "$iconset" -o "$resources/AppIcon.icns"
}
# Generate the icon before writing bundle metadata.
create_icon
# Assemble the bundle property list.
cat > "$contents/Info.plist" <<INFO_PLIST
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version='1.0'>
<dict><!-- CodexBuddy bundle metadata -->
  <key>CFBundleDevelopmentRegion</key><string>zh_CN</string>
  <key>CFBundleExecutable</key><string>$product_name</string>
  <key>CFBundleIdentifier</key><string>$bundle_identifier</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>$product_name</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$release_version</string>
  <key>CFBundleVersion</key><string>$release_build</string>
  <key>LSApplicationCategoryType</key><string>public.app-category.developer-tools</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict><!-- end CodexBuddy metadata -->
</plist><!-- generated by the v0.7 builder -->
INFO_PLIST
# Validate the generated metadata before reporting success.
plutil -lint "$contents/Info.plist" >/dev/null
echo "$application_bundle"
